#!/bin/bash
# shellcheck disable=SC1090,SC2068
# cSpell:disable

# MAINIF is the name of server's main interface which is connected to the internet.
# DIR is related to clients. (client's folder)
# INTERFACE is the name of wireguard interface.

# TO DO:
# -> add firewall function on "delif"

set -uo pipefail

BASEDIR='/etc/wireguard'
DEFAULTIF="wg0"
DEFAULTDNS="8.8.8.8"
ALLOWED_IPS="0.0.0.0/0"

YELLOW='\033[0;33m'
DECOLOR='\033[0m'
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'

DEL='No'
declare -i PORT

err() {
    echo -e "$1" >&2
    exit "${2:-1}"
}

find_mainif() {
    # Sets variable "MAINIF" to the name of the network interface through which 
    # system connects to internet.
    # mapfile -t iflist < <(find /sys/class/net/ | rev | cut -d / -f1 | rev | sed '/^$/d')
    # mapfile -t tmp < <(\ip route |grep default |sed -e 's/^\s*//;s/\s/\n/g;')

    # for var in "${tmp[@]}"; do
    #     [[ " ${iflist[*]} " =~ ${var} ]] && MAINIF=$var
    # done
    MAINIF=$(\ip -4 route show default 2>/dev/null | \
        awk '{for(i=1;i<=NF;i++) if ($i=="dev") {print $(i+1); exit}}')
    if [[ -z $MAINIF ]]; then
        echo -e "\nCouldn't determine the main interface on the system.\n" >&2
        return 1
    fi
}

checkuser() {
    [[ $UID == "0" ]] || err "You are not root." "1"
}

os() {
    grep -e '^ID=' /etc/os-release \
        | cut -d = -f 2 | sed -e 's/[[:punct:]]//g' \
        | tr "[:upper:]" "[:lower:]"
}

install_pkg() {
    echo -e "\nInstalling $*..."
    case $(os) in
        centos | fedora | almalinux | rocky)
            yum -y install $@ 2>/dev/null || dnf -y install $@ || return 3
            sleep 1
            ;;
        ubuntu | debian)
            apt update
            apt -y install "$@" || return 3
            sleep 1
            ;;
        manjaro | endeavouros | arch*)
            pacman -Sy --noconfirm $@ || return 3
            sleep 1
            ;;
    esac
}

getifip() {
# Returns IP of a given interface.
# Usage: getifip <interface>
\ip -4 a show dev "$1" | grep 'inet ' | head -n 1 | awk '{print $2}' | cut -d / -f 1
}

enable_ipforward() {
# Checks and enables ip forwarding kernel parameter.
echo "Checking net.ipv4.ip_forward..."
if grep '0' /proc/sys/net/ipv4/ip_forward >/dev/null; then
    echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
    sysctl -p > /dev/null 2>&1 || return 1
fi
}

read_parameters() {
    case $1 in
        addif)
            read -r -p "Enter IP for interface: " IFLOCALIP
            while ip -4 a | grep 'inet ' | awk '{print $2}' | grep "$IFLOCALIP" > /dev/null
            do
                echo -e "\nIP address in use. Try a different one.\n"
                read -r -p "Enter IP for interface: " IFLOCALIP
            done
            read -r -p "Enter listening port: " PORT
            while ss --no-header -4lun | awk '{print$4}' | cut -d : -f2 | grep "$(getifip "$MAINIF")":$PORT > /dev/null \
                || ! ((1 < PORT && PORT < 65536))
            do
                echo -e "\nBusy or invalid port. Try a different port number.\n"
                read -r -p "Enter listening port: " PORT
            done
            ;;
        adduser)
            tmpip=$(calculate_ip)
            [[ $tmpip == "range_full" ]] && err "\nIP range full. Please delete a user." "1"
            read -r -p "Enter client Wireguard IP: [$tmpip] " LOCALIP
            while grep "$LOCALIP" $BASEDIR/"${INTERFACE}".conf > /dev/null && [[ -n $LOCALIP ]]
            do
                echo -e "\nIP address in use. Try a different one.\n"
                read -r -p "Enter client Wireguard IP: [$tmpip] " LOCALIP
            done
            [[ -z $LOCALIP ]] && LOCALIP=$tmpip
            read -r -p "Enter client's DNS server IP: [$DEFAULTDNS] " DNS
            [[ -z $DNS ]] && DNS=$DEFAULTDNS
            ;;
    esac
}

calculate_ip() {
    declare -i o1 o2 o3 o4
    IFIP=$(grep 'Address' $BASEDIR/"$INTERFACE".conf | awk '{print$3}' | cut -d / -f1)
    IFS=. read -r o1 o2 o3 o4 <<< "$IFIP"
    ((o4++))
    while grep $o1.$o2.$o3.$o4/ $BASEDIR/"$INTERFACE".conf > /dev/null
    do
        ((o4++))
    done
    (( o4 > 254 )) && { echo "range_full"; return; }
    echo "$o1.$o2.$o3.$o4"
}

set_variables() {
    mkdir -p "$DIR"
    if ! test -f "$DIR"/"$USERNAME".key; then
        wg genkey | tee "$DIR"/"$USERNAME".key | wg pubkey | \
        tee "$DIR"/"$USERNAME".key.pub > /dev/null
    else
        echo -en "${YELLOW}\nA private key already exists in \"$DIR\" for given username. "
        echo -e "We'll use that key."
        echo -en "${YELLOW}If you prefer a new key please manually remove the "
        echo -e "file: \"$DIR/$USERNAME.key\""
        echo -e "${YELLOW}then try again.\n${DECOLOR}"
        wg pubkey < "$DIR"/"$USERNAME".key | tee "$DIR"/"$USERNAME".key.pub > /dev/null
    fi

    CLIENT_PRIVATE_KEY=$(cat "$DIR"/"$USERNAME".key)
    CLIENT_PUBLIC_KEY=$(cat "$DIR"/"$USERNAME".key.pub)
    SERVER_PUBLIC_KEY=$(wg show "$INTERFACE"| grep "public key" | cut -d ':' -f 2 | sed 's/^\s//')
    [[ $SERVER_PUBLIC_KEY != "" ]] || \
        err "${RED}Error fetching server's public key.${DECOLOR}" "1"
    PORT=$(wg show "$INTERFACE" | grep "listening port" | cut -d ':' -f 2 | sed 's/^\s*//')
}

generate_configs() {
    cat << EOF > "$DIR"/"${USERNAME}".conf
[Interface]
PrivateKey = $CLIENT_PRIVATE_KEY
Address = ${LOCALIP}/32
DNS = ${DNS}

[Peer]
PublicKey = $SERVER_PUBLIC_KEY
AllowedIPs = ${ALLOWED_IPS}
Endpoint = $(getifip "$MAINIF"):$PORT
EOF

    cat << EOF >> $BASEDIR/"$INTERFACE".conf
[Peer]
# $USERNAME
PublicKey = $CLIENT_PUBLIC_KEY
AllowedIPs = ${LOCALIP}/32
EOF
    qrencode -s 6 -o "$DIR"/"$USERNAME".png < "$DIR"/"$USERNAME".conf
}

generate_interface_config() {
    mkdir -p $BASEDIR; chmod 0700 $BASEDIR
    if [[ -f $BASEDIR/$INTERFACE/$INTERFACE.privatekey ]]; then
        echo -en "${YELLOW}\nA private key already exists in \"$BASEDIR\" for given interface. "
        echo -e "We'll use that key."
        echo -en "${YELLOW}If you prefer a new key please manually remove the file: "
        echo -e "\"$BASEDIR/$INTERFACE/$INTERFACE.privatekey\""
        echo -e "${YELLOW}then try again.\n${DECOLOR}"
    else
        mkdir -p $BASEDIR/"$INTERFACE"
        umask 077; wg genkey | tee $BASEDIR/"$INTERFACE"/"$INTERFACE".privatekey | \
            wg pubkey > $BASEDIR/"$INTERFACE"/"$INTERFACE".publickey
    fi
    cat << EOF > $BASEDIR/"$INTERFACE".conf
[Interface]
Address = ${IFLOCALIP}/24
ListenPort = ${PORT}
PrivateKey = $(cat $BASEDIR/"$INTERFACE"/"$INTERFACE".privatekey)
PostUp = iptables -I INPUT -p udp --dport $PORT -j ACCEPT; \
iptables -I FORWARD -o %i -j ACCEPT; \
iptables -I FORWARD -i %i -j ACCEPT; \
iptables -t nat -A POSTROUTING -o $MAINIF -j MASQUERADE
PostDown = iptables -D INPUT -p udp --dport $PORT -j ACCEPT; \
iptables -D FORWARD -o %i -j ACCEPT; \
iptables -D FORWARD -i %i -j ACCEPT; \
iptables -t nat -D POSTROUTING -o $MAINIF -j MASQUERADE
EOF
}

usage() {
    echo -e "\nUsage: ${0##*/} <adduser|deluser> USERNAME [INTERFACE]" >&2
    echo -e "       ${0##*/} <addif|delif> [INTERFACE]" >&2
    echo -e "       ${0##*/} lsif" >&2
    echo -e "       ${0##*/} lsuser [INTERFACE]" >&2
    echo -e "       ${0##*/} getuser USERNAME [INTERFACE]" >&2
    echo -e "       ${0##*/} backup [INTERFACE]" >&2
    echo -e "       ${0##*/} restore <path_to_backup>" >&2
    echo -e "       ${0##*/} install\n" >&2
}

removeuser() {
    set +o pipefail
    ln=$(grep -nm 1 "^# $USERNAME$" "$BASEDIR/$INTERFACE.conf" | cut -d : -f 1)
    set -o pipefail
    if [[ -n $ln ]]; then
        sed -i "$((ln-1)),$((ln+2))d" "$BASEDIR/$INTERFACE.conf"
    else
        err "No such user." "1"
    fi
}

checkname() {
    if ! grep -e "# ${USERNAME}$" "$BASEDIR/$INTERFACE.conf"; then
        echo ok
    fi
}

check_interface_exists() {
    if [[ -f $BASEDIR/$INTERFACE.conf ]]; then
        echo "exists"
    fi
}

startmsg() {
    find_mainif
    while :
    do
        echo -en "\nInterface ${BLUE}[$MAINIF]${DECOLOR} with IP address "
        echo -en "${BLUE}[$(getifip "$MAINIF")]${DECOLOR}"
        echo -e " is selected as main external interface for this server."
        read -r -p "Do you wish to continue? [Y/n]" START
        echo ""
        { [[ $START =~ ^[yY] ]] || [[ $START == "" ]]; } && break
        [[ $START =~ ^[nN] ]] && exit
    done
}

check_wireguard_installed() {
    wg -v > /dev/null 2>&1 || { echo -e "${RED}\n\"Wireguard\" is not installed." >&2;
        echo -e "${RED}You can run this command to install it:\n" >&2;
        err "${RED}       $0 install\n${DECOLOR}" "1"; }
}

check_qrencode_installed() {
    qrencode -V > /dev/null 2>&1 || \
        err "${RED}\n\"qrencode\" is not installed.\n${DECOLOR}" "1"
}

###################################################################################################

if [[ $1 == "--help" ]] || [[ $1 == "-h" ]]; then
    usage
    exit
elif [[ $1 != "install" ]] \
    && [[ $1 != "lsif" ]] \
    && [[ $1 != "lsuser" ]] \
    && [[ $# -lt 2 ]]; then
    err "${RED}\nInsufficient parameters.\n${DECOLOR}" "1"
fi

unset command_not_found_handle

checkuser

case $1 in
    adduser | deluser)
        check_wireguard_installed
        USERNAME=$2
        INTERFACE=${3:-$DEFAULTIF}
        
        # Check if all parameters are present:
        if [[ -z $USERNAME ]] || [[ -z $INTERFACE ]]; then
            usage
            exit 1
        fi
        # Check if given INTERFACE exists:
        [[ $(check_interface_exists) == "exists" ]] || err "${RED}Invalid Interface.${DECOLOR}" "1"
        
        DIR="$BASEDIR/$INTERFACE/clients/$USERNAME"
        
        case $1 in
            adduser)
                check_qrencode_installed
                startmsg
                read_parameters "$1"
                [[ $(checkname) == "ok" ]] || err "${RED}Username exists.${DECOLOR}" "1"
                set_variables
                generate_configs
                systemctl reload-or-restart wg-quick@"$INTERFACE".service
                echo -e "${GREEN}\nUser added successfully!${DECOLOR}"
                echo -e "${GREEN}\nUse this config on your client side:\n${DECOLOR}"
                cat "$DIR/$USERNAME.conf"
                echo -e "${GREEN}\nor this QR code:\n${DECOLOR}"
                qrencode -t UTF8 < "$DIR/$USERNAME.conf"
                ;;
            deluser)
                [[ -d $DIR ]] \
                    && { echo -en "Do you want to delete all user's configuration files? [y/N] "
                        read -r DEL; }
                [[ $DEL =~ ^[yY] ]] && rm -rf "$DIR"
                removeuser
                systemctl reload-or-restart wg-quick@"$INTERFACE".service
                echo -e "${GREEN}User \"$USERNAME\" removed successfully.${DECOLOR}"
                ;;
        esac
        ;;
    lsuser)
        tmp_output=/tmp/wg.txt
        INTERFACE=${2:-$DEFAULTIF}
        WG_COLOR_MODE=always wg show "$INTERFACE" > "$tmp_output" || \
            { rm -f "$tmp_output"; exit 1; }
        while IFS= read -r user; do
            sed -i "s/$(cat "$user"/*.key.pub | sed 's/\//\\\//g')/${user##*/}/g" "$tmp_output"
            # sed 's/\//\\\//g' replaces all '/' characters with '\/'  so the 
            # parent sed does work properly.
        done < <(find "$BASEDIR/$INTERFACE/clients/" -maxdepth 1 -mindepth 1)
        cat "$tmp_output"; rm -f "$tmp_output"
        ;;
    getuser)
        check_qrencode_installed
        USERNAME=$2
        INTERFACE=${3:-$DEFAULTIF}
        DIR="$BASEDIR/$INTERFACE/clients/$USERNAME"

        [[ ! -d $DIR ]] && \
            err "${RED}User doesn't exist on interface \"$INTERFACE\".${DECOLOR}" "1"

        echo -e "${GREEN}\nUse this config on your client side:\n${DECOLOR}"
        cat "$DIR"/"${USERNAME}".conf
        echo -e "${GREEN}\nor this QR code:\n${DECOLOR}"
        qrencode -t UTF8 < "$DIR/$USERNAME.conf"
        ;;
    addif | delif)
        check_wireguard_installed
        INTERFACE=${2:-$DEFAULTIF}
        case $1 in
            addif)
                startmsg
                read_parameters "$1"
                ! [[ $(check_interface_exists) == "exists" ]] || err "Interface exists." "1"
                generate_interface_config
                set -x
                systemctl enable wg-quick@"$INTERFACE".service
                systemctl start wg-quick@"$INTERFACE".service || \
                    { set +x; err "Failed to start unit."; }
                set +x
                echo -e "${GREEN}\n$INTERFACE: Successfully configured.${DECOLOR}\n"
                ;;
            delif)
                read -r -p "Removing interface \"$INTERFACE\". Are you sure? [y/N] " SURE
                ! [[ $SURE =~ ^[yY] ]] && exit 0
                set -x; systemctl stop wg-quick@"$INTERFACE".service; set +x;
                read -r -p "Do you want to delete all related configuration files? [y/N] " DEL
                if [[ $DEL =~ ^[yY] ]]; then
                    set -x; rm -rf "$BASEDIR/${INTERFACE:?}"; set +x;
                else
                    echo -e "\nConfiguration files are remaining on the system."
                    echo -e "You can remove key files located in \"$BASEDIR\" manually.\n"
                fi
                set -x; rm -f "$BASEDIR/$INTERFACE.conf"; set +x;
                echo -e "${GREEN}\nSuccessfully removed \"$INTERFACE\".${DECOLOR}"
                ;;
        esac
        ;;
    lsif)
        check_wireguard_installed
        wg show interfaces
        ;;
    install)
        wg -v > /dev/null 2>&1 && err "${YELLOW}\nAlready installed!\n${DECOLOR}" "1"
        enable_ipforward
        case $(os) in
            centos)
                install_pkg epel-release
                install_pkg elrepo-release
                install_pkg yum-plugin-elrepo
                install_pkg kmod-wireguard
                install_pkg wireguard-tools
                ;;
            ubuntu | debian)
                install_pkg wireguard
                ;;
            fedora | almalinux | rocky)
                install_pkg wireguard-tools
                ;;
            *)
                echo -e "${RED}Automatic installation is not supported for your distribution." >&2
                echo -en "${RED}Please follow instructions here to " >&2
                echo -e "install \"Wireguard\" manually:" >&2
                err "${RED}https://www.wireguard.com/install/\n${DECOLOR}" "1"
                ;;
        esac
        ;;
    backup)
        INTERFACE=${2:-$DEFAULTIF}
        current_dir="$PWD"
        cd "$BASEDIR" || err "Couldn't access $BASEDIR" "1"
        tar -cf "${HOSTNAME}_${INTERFACE}.backup.tar ./$INTERFACE"* && \
            echo -e "Backup created: $BASEDIR/${HOSTNAME}_${INTERFACE}.backup.tar"
        cd "$current_dir" || exit 1
        ;;
    restore)
        BACKUP_FILE=$2
        [[ $(file -b --extension "$BACKUP_FILE") == "tar/gtar" ]] || \
            err "Invalid backup file: $BACKUP_FILE" "1"
        current_dir="$PWD"
        cp "$BACKUP_FILE" "$BASEDIR"
        cd "$BASEDIR" || err "Couldn't access $BASEDIR" "1"
        tar -xf "$BASEDIR/${BACKUP_FILE##*/}"
        rm "$BASEDIR/${BACKUP_FILE##*/}"
        echo -e "${GREEN}Restored successfully.${DECOLOR}"
        echo -e "You may start using the interface via:"
        echo -e "\n    systemctl enable --now wg-quick@${BOLD}<INTERFACE>${DECOLOR}.service.\n"
        cd "$current_dir" || exit 1
        ;;
    *)
        usage
        exit 1
        ;;
esac